name: compress

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: resourcepack

      - name: compress pack
        uses: yuyaprgrm/resourcepack-compressor@v2.1
        with:
          source: resourcepack
          destination: artifact
          pack-name: InventoryUIResourcePack
          minify: true

      - name: Upload a Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifact/InventoryUIResourcePack.mcpack
